version: '3.9'
services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - './pg:/var/lib/postgresql/data'
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '9000:80'
    depends_on:
      - postgres
    volumes:
      - './pgadmin:/var/lib/pgadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
